### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by Bergrebell** [felipesousa/wunderlist-api#3]
hi guys. thanks for publishing your project! :)

when trying to authenticate with my clientID/accessToken I get an error saying:

```
body: '{"error":{"type":"server_error","translation_key":"api_error_unknown","message":"An unknown server error occurred","authentication":["missing"]}}' }
```

here's my code:

```
"use strict";

const Wunderlist = require("wunderlist-api");

const wunderlist = new Wunderlist({
  clientID: "xxx",
  accessToken: "xxx"
});

// authentication
wunderlist
  .user()
  .then(response => {
    // response
    console.log(response);
  })
  .catch(error => {
    // handle error
  });
```
what am i doing wrong?

**Comment by aleksandrguru** [comment]
var Wunderlist = require ('wunderlist-api');
  const wunderlist = new Wunderlist({
    clientId: '0f812c1d7c07c3a83f32',
    accessToken: '900889059e9b68aa489fcf84bd1457e233137943813940f2d5789bfba9df'
  })

  // authentication
wunderlist.user()
.then( response => {
  console.log(response);
})
.catch( error => {
  console.log(error);
});

**Comment by seoeaa** [comment]
var Wunderlist = require ('wunderlist-api');
  const wunderlist = new Wunderlist({
    clientId: '7678789',
    accessToken: '7687787980'
  })

  // authentication
wunderlist.user()
.then( response => {
  console.log(response);
})
.catch( error => {
  console.log(error);
});

**Comment by felipesousa** [comment]
@Bergrebell thanks for reporting it, the issue keep happen?

**Comment by seoeaa** [comment]
"use strict" if you remove it works

**Comment by bencevans** [comment]
I ran into the same issue. Found it to be I was trying to use `clientID` rather than what this library accepts which is `clientId` (lowercase d in id).
